### PR TITLE
fix: Stacks deployed with CDK versions earlier than 1.93.0 cause an error, and are not detected correctly

### LINKED ISSUE #8: Stacks deployed with versions earlier than 1.93 cause TypeError: Cannot read properties of undefined (reading 'split')
Hi,

Using this tool to scan for V1 CDK stacks. Works fine on most of my accounts, however on one of the accounts I am getting the following error:

```bash
TypeError: Cannot read properties of undefined (reading 'split')
    at findV1Stacks (.npm/_npx/1a70b0cb204f1c57/node_modules/awscdk-v1-stack-finder/lib/index.js:149:85)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async processListStacksResponse (.npm/_npx/1a70b0cb204f1c57/node_modules/awscdk-v1-stack-finder/lib/index.js:122:5)
    at async find (.npm/_npx/1a70b0cb204f1c57/node_modules/awscdk-v1-stack-finder/lib/index.js:94:9).
```

It's going wrong in the following function:
```js
async function findV1Stacks(response, cloudformation, region, stacks) {
    var _a;
    for (const stack of (_a = response.StackSummaries) !== null && _a !== void 0 ? _a : []) {
        const getTemplateResponse = await cloudformation.getTemplate({
            StackName: stack.StackName,
        }).promise().catch((error) => console.error(`${region}: Failed to get template for stack: ${stack.StackName}. Error: ${error}`));
        var body;
        try {
            body = JSON.parse(getTemplateResponse.TemplateBody);
        }
        catch (err) {
            body = YAML.parse(getTemplateResponse.TemplateBody);
        }
        if (body.Resources.CDKMetadata) {
            const buf = Buffer.from(body.Resources.CDKMetadata.Properties.Analytics.split(':').splice(2)[0], 'base64');
            const analyticsString = zlib.gunzipSync(buf).toString();
            const majorVersion = analyticsString.slice(0, 1);
            if (majorVersion === '1') {
                stacks.push(`name: ${stack.StackName} | id: ${stack.StackId}`);
            }
        }
    }
}
```

Something is causing `body.Resources.CDKMetadata.Properties.Analytics` to be `undefined`.

- I am assuming a role with all permissions and no explicit denies using the `aws sts assume-role` api.
- I am using the env variable to set the credentials after.
```bash
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
export AWS_SESSION_TOKEN=...
```
- I verified the account has `CDKToolkit` stacks.
-  Node.js version v16.14.2, npm version 8.5.0

### PR DESCRIPTION
**Pull request by madeline-k**
…
Fixes #8

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -148,10 +148,21 @@ async function findV1Stacks(
       body = YAML.parse(getTemplateResponse.TemplateBody);
     }
     if (body.Resources.CDKMetadata) {
-      const buf = Buffer.from(body.Resources.CDKMetadata.Properties.Analytics.split(':').splice(2)[0], 'base64');
-      const analyticsString = zlib.gunzipSync(buf).toString();
-      const majorVersion = analyticsString.slice(0, 1);
-      if (majorVersion === '1') {
+      let stackUsedV1 = false;
+      if (body.Resources.CDKMetadata.Properties?.Analytics) {
+        var buf = Buffer.from(body.Resources.CDKMetadata.Properties.Analytics.split(':').splice(2)[0], 'base64');
```
Comment (iliapolo) [inline src/index.ts:153]:
```suggestion
        const buf = Buffer.from(body.Resources.CDKMetadata.Properties.Analytics.split(':').splice(2)[0], 'base64');
```

File: src/index.ts [hunk 2]
```diff
@@ -148,10 +148,21 @@ async function findV1Stacks(
...
+        if (!buf) {
+        }
```
Comment (iliapolo) [inline src/index.ts:155]: Leftover?

**Review by iliapolo — APPROVED** [review]
Small cleanup stuff, approving with `do-not-merge` 👍
